### ISSUE TITLE
프로젝트 주제 정하기

### ISSUE THREAD

**Issue by songwon0327** [songwon0327/industrial-project#1]
주제 1 : 고독사 방지 모션감지 알림이
-> 이용자가 자주 이동하는 동선에 센서 설치
-> 일정 기간 센서에 이용자가 감지되지 않으면 어플에 저장된 보호자의 번호로 알림 전송
->  외출 시에는 어플 내에서 알림 전송 기능을 끌 수 있도록 (오작동 방지)

**Comment by LBKME** [comment]
아이디어 좋은 것 같습니다. 그런데 제가 특허를 찾아본 결과 이와 같은 아이디어가 실제 특허로 등록되어있어서 만약 이 아이디어로 주제를 잡게 된다면 차별화 전략을 세워야 할 것 같습니다.

**Comment by DaHyun0110** [comment]
월요일에 생각한 내용 정리한것도 함께 올립니다!

이범구 - 키오스크에를 잘 다루시지 못하는 어른 들을 위하여 , 키오스크 입력 시간이 지연되는 것과 같이 어르신으로 추측되는 상황을 모니터링 하여 음성인식으로 주문을 돕는 시스템.
          황다현 - 해당 의견에 추가를 하여 우유부단한 사람을 위하여 음식을 추천 해주거나 (기본적으로 있기는 함) 어르신들의 경우 직원을 호출 할 수 있는 알람까지 설정하면 좋을 것 같음.

 

이범구 - 시각 장애인 유도점자 블록이 훼손되는 경우 일반인과 시각 장애인의 걸음속도등을 압력으로 모니터링하여 시각 장애인일 경우 엉뚱한 방향으로 갈시 경고 알람을 줌.

**Comment by DaHyun0110** [comment]
해당 주제는 시각 장애인에게 유도 점자블록이 훼손과 관련된 주제로 결정되었습니다.
