### ISSUE TITLE
개발 역할 분담 및 모듈 나누기

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#10]
역할을 분담하기 위하여 모듈을 나누는게 어떤가 싶습니다.
제가 생각한것은
1. 신호등 ON OFF - 어플 연결
2. ESP32를 통하여 신호등의 입력을 받기(블루투스, ON-OFF만 사용)
3. 무게센서 - 제 생각 입니다!
   3-1. 무게감지하여 좌표로 나타내기.
   3-2. 감지한 무게를 방향으로 나타내기
   3-3. 방향을 차도와의 각도로 환산해서 차도쪽으로 1~179도로 갈 시 알림 울리도록하기.
4. 알림.(목소리를 입력받아 필요할떄 출력하는것.)
 4-2. 위험상황일때나 다른 상황일때 출력함. ex) EmerAlram()
5. 블록에 대한 물리회로도 납땜및 만들기

위는 모두 각자가 메인을 하나씩 맡고, 다른 분들도 생각나는 아이디어가 있을시 함께 도우면 좋겟다고 생각됩니다!

3번은 자세한 토론이 필요할 것 같아 다른 이슈로 작성하였으니 한번 확인 부탁드립니다.
@DobakJungdok @songwon0327 @LBKME

**Comment by DobakJungdok** [comment]
@songwon0327 @LBKME @DobakJungdok

**Comment by DaHyun0110** [comment]
3번이 저희의 기술이 집약되어 있는 부분이라고 생각 되어 제가 1 2 4 번을 맡고 3번은 최고 책임자를 정한 뒤 다른 사람들이 도와주는 것으로 하는 것이 나을 것이라 생각이 됩니다!

**Comment by LBKME** [comment]
일단 제가 5. 물리회로와 납땜 부분을 맡겠습니다.

**Comment by songwon0327** [comment]
일단은 제가 3번을 먼저 맡아서 개발해보겠습니다.
