### ISSUE TITLE
무게센서를 인식하여 위험한 상황을 감지하게 하는 방법 - 인공지능 유무에 대하여

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#11]
초반에는 인공지능 분류모델을 쓰기로 하였지만,
제가 생각 해본 바, 저희는 모니터링이 우선적이고, 인공지능 없이도 할수 있겠다고 생각이 되어 인공지능 없이 한번 해보는 것도 나쁘지 않다고 생각이 듭니다.
없이 한다는 전제하에 제가 생각한 방법입니다. 이에 대한 의견이 있으시면 토론 부탁드립니다.

아두이노를 잘 사용해본 적이 없기때문에 안될수도 있는점 참고 부탁드립니다!

1. 무게를 감지
2. 감지한것을 바탕으로 좌표로 나타내기(좌표는 센서의 민감도에 따라 센서의 위치대로인 4개의 좌표나 사람이 발을 딛는 부분에 따라 여러 좌표로 나타 낼 수 있을것 같습니다.)
3. 처음 찍힌 좌표와 뒤에 찍힌 좌표를 통하여 방향을 나타내기
한번에 쫙 찍힐 경우도 생각을 해 보아야할것 같습니다!
저는 이럴때도  위험 상황으로 생각하는것이 좋다고 봅니다.
4. 방향을 잡아 차도쪽으로 1˚~179˚일 때 경고알림이 울리도록 한다.

@songwon0327 @DobakJungdok @LBKME

**Comment by LBKME** [comment]
좌표로 나타내는 것은 어려울 것으로 예상됩니다. 가격이 저렴한 로드셀이라서요

**Comment by songwon0327** [comment]
저도 인공지능 없이도 구현이 충분히 가능하다고 생각하기 떄문에 굳이 사용할 필요 없다고 생각합니다.

**Comment by DaHyun0110** [comment]
이번 개발에선 우선적으로 인공지능을 사용하지 않는 코드를 짯습니다. @songwon0327 @DaHyun0110 @LBKME
