### ISSUE TITLE
아이디어 배틀그라운드 공모전 일전과 세부사항에 대해

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#12]
아이디어 배틀그라운드 공모전이 2일 전입니다. 현재 신청서 작성이 끝났고 참여자들의 전화번호 메일주소가 필요합니다.

일정은 19일까지 제출, 28일 발표입니다. 숙지하셨으면 합니다

**Comment by DaHyun0110** [comment]
01022008509 erica0359@naver.com

**Comment by songwon0327** [comment]
01044341690 / songwon12495@gmail.com 입니다.
