### ISSUE TITLE
로드셀 무게 출력 문제

### ISSUE THREAD

**Issue by songwon0327** [songwon0327/industrial-project#13]
무게 출력 시 83388607이란 수 만 계속 출력되고 무게를 더하거나 뺴도 값이 바뀌지 않습니다. 검색해봐도 사례가 잘 나오지 않아서 이유를 잘 모르겠습니다. 혹시 해결책 알고 계신 분 있으실까요?

**Comment by LBKME** [comment]
설계당시 HX711 inverter을 사용하여 무게 셀의 측정값을 증폭시켰습니다. 
https://blog.danggun.net/7562
이 블로그 참고하시면 좋을 듯 합니다
