### ISSUE TITLE
Peer review team관련

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#14]
저희팀은 ROOT팀에게 review를 줘야합니다.

ROOT팀은 화분습도 모니터링 시스템을 만드려는 팀입니다. 자료는 이곳에 올라가지 않아서 단톡으로 공유하겠습니다.

어떤 내용을 보낼지에 대해 의견주시길 바랍니다

**Comment by DaHyun0110** [comment]
다소 억지일수 있는 부분도 있을수 있으니 다들 한번 확인 해주시면 감사하겠습니다! ㅎㅎ
저는 지적에 중심을 둬 칭찬의 부분이 조금 모자라여 다른 분들께서 찾아주시면 좋을 것 같습니다! 

(1) 자의든 타의든 식물을 키우면서 물 조절의 면에서 잘 되지 않아 시든적이 많은 이들에게 있을것인데, 수분을 측정하여 더욱 과학적으로 알려준다는 면이 매력적이라 생각됩니다.

Evaluation / Contribution: 여러센서를 추가한다고 하셨는데, 명시하였던 이전의 기술 중 스마트 화분이라는 것과 기능면에서 많은 부분이 닮아 있다는 생각이 듭니다. 이에 대하여 차별을 두면 좋지 않을까 생각됩니다. 

Solution: 농사로 사이트에는 농업자료가 주 축을 이루고 있어, 타겟으로 삼으시는 일반인 식물 애호가들에게 필요해 보이는 정보는 사이트에 명시되어있는 실내에서 키우는 방법정도로 보입니다. 물론 해당 방법도 알려준다는 점이 실내에서 어찌 키워야하나 고민하시는 분들께 많은 도움이 될것이라고 생각이 듭니다. 하지만, 해당 사용자가 키우는 식물에 대한 자세한 사항이 더 들어나면 좋겟다 생각이 됩니다! 혹여나 농사로에서 제가 찾아 본것이 전부라면, 각 식물들에 대한 정보를 인터넷 어플리케이션과 연동하여 url 검색을 통하여 검색하는 기능도 있었으면 싶습니다.
예시) 제가 사용하는 음식 칼로리 입력 어플에서는 해당 음식을 검색하면, 인터넷 어플리케이션으로 이동하여 자동으로 칼로리가 몇인지 검색하여 줍니다. 

그 외1: 이메일 ID를 사용하는 경우 별 다른 보안장치가 없다면 개인정보가 들어나는 위험이 있지 않을까 생각됩니다. 이메일이 없는 일반 ID로 가입을 하고, 아이디 중복확인을 하는 시스템은 어떨까 싶습니다.

그 외2: I/D, P/W만 입력하고 가입이 되는 경우, 계정 비밀번호를 분실하였을 시에 대한 기능은 없어 ID로 임시 비밀번호 이메일을 보내거나, 비밀번호 찾기용 질문을 만드는 것은 어떨까 싶습니다.

Problem: 초반의 기획을 보면 수분 부족 알람이지만, 개선사항의 여러 센서들을 추가하는것으로 보입니다. 이는 수분 부족에는 필요없는 여타 다른 관리를 위해 필요한 센서들로 보이는데, 이에 대하여 아웃풋을 조금 조정해야할 듯 싶습니다.

혹여나 이해가 안가시는 부분은 카톡+ 어사인 부탁드립니다!

**Comment by songwon0327** [comment]
1) Problem, Solution, 차별성 등에 대하여 자신의 언어로 설명하기
취미로 식물을 키우는 사람들은 전문지식을 가지고 있지 않기 때문에 얼마 주기로 물을 줘야하고 어떻게 관리해야 하는지 모르는 경우가 많아서 따로 인터넷이나 책을 통해 공부해야한다는 어려운 점이 있는데 화분 습도 모니터링 서비스는 토양 습도를 실시간으로 알려주고 식물 관리법을 한 애플리케이션에서 모두 지원한다는 점이 장점이라고 생각되었다. 

2) 차별성 관련
엔씽이라는 기업에서 판매하고 있는 planty라는 스마트 화분이 있습니다. planty는 땅의 습도와 온도를 파악해서 애플리케이션을 통해 확인할 수 있고 화분 자체에 물통이 있어 원격으로 물주기도 가능한 화분입니다. 이러한 점에서 토양의 습도만 모니터링 가능한 서비스는 차별성이 부족하다고 여겨지고 기존 제품이 물주기 기능까지 있다는 점에서 아닌 ROOT 팀의 서비스를 이용해야만 할 이유가 부족하다고 느껴집니다. 

3) solution 관련
식물에 따라 적합한 습도의 정도가 다를 텐데 (예를 들어 선인장의 경우에는 물을 주는 주기가 매우 길고 습도가 낮아야함) 단순히 토양의 습도를 파악해서 습도가 낮을 경우 알림을 주는 것이 아쉽다고 느껴집니다. 식물마다 습도 낮음 알림의 기준을 설정해야 할 것 같고 이를 정확하게 명시해주어야 할 것 같습니다. 

4) 그 외 : 토양의 습도를 단순히 텍스트로 명시하는 것이 아닌 그림과 함께 습도에 따라 문구가 바뀐다는 부분이 사용자에게 큰 재미 요소가 될 것으로 생각됩니다. 더 나아가 습도에 따라 문구와 함께 실행 화면의 화분의 표정이 바뀌는 등의 요소를 넣으면 더욱 좋을 것 같습니다.
