### ISSUE TITLE
feedback 받은 peer-review와 관련하여

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#15]
저희는 개발시간과 프로그램상의 응답시간 등의 이유로 인공지능의 개발을 조금더 생각해보자는 방향으로 결정 되었습니다.

허나, 이번 peer-review에서 아쉬운 점과 차별점으로 인공지능에 대하여 받았기 때문에 이에 대하여 저희가 어떻게 반영할지에 대하여 생각해 보아야 할 것 같습니다.
@DobakJungdok @LBKME @songwon0327

**Comment by DaHyun0110** [comment]
인공지능 - 반대
1. 개발 시간상의 이유
2. 인공지능이 없어도 충분히 좌표를 통하여 위험상황임을 알수 있음. 인공지능을 넣어서 얻을수 있는 메리트가 있는지 확인 해 보아야할것임. (계산이 빨라지는가 등)

때문에 상대팀에서 차별성이 인공지능이라 하신 부분에 대하여 납득하실만한 다른 차별점을 찾아야할것 같습니다. 저 또한 완벽한 차이점을 생각해보겠급니다

**Comment by LBKME** [comment]
기사나 통계 자료를 이용하면 좋을 것 같다 - http://www.joongboo.com/news/articleView.html?idxno=363558424
이 기사내용을 넣으면 좋을 것 같습니다.
무게중심의 방향을 어떻게 보여줄 것인가 - 센서의 한계로 불가능하다 판단.
인도에 차량이 올라오는 것을 버틸 수 있는가? - 일단 차가 올라오는 것을 물리적으로 막는 방법이 있으나 블록을 개발하는 것으론 어렵고 교착상태(dealock)알고리즘의 해결책방법중 하나인 ostrichargorithm처럼 일어나지 않기를 바라는 정도로 마무리
인공지능을 넣지 않은 이유 - 1. 센서의 한계(어떤 센서에 얼마만큼의 무게가 측정되는지 알기 위해서는 HX711를 여러개 연결해야하지만, 예산상, 시간상의 이유로 어려움)
2. 응답시간의 문제점 - 응답시간이 길어지면 알림을 울리는 타이밍이 늦어 위험요소가 존재할 수 있음

**Comment by LBKME** [comment]
기사나 통계 자료를 이용하면 좋을 것 같다 - http://www.joongboo.com/news/articleView.html?idxno=363558424
이 기사내용을 넣으면 좋을 것 같습니다.
무게중심의 방향을 어떻게 보여줄 것인가 - 센서의 한계로 불가능하다 판단.
인도에 차량이 올라오는 것을 버틸 수 있는가? - 일단 차가 올라오는 것을 물리적으로 막는 방법이 있으나 블록을 개발하는 것으론 어렵고 교착상태(dealock)알고리즘의 해결책방법중 하나인 ostrichargorithm처럼 일어나지 않기를 바라는 정도로 마무리
인공지능을 넣지 않은 이유 - 1. 센서의 한계(어떤 센서에 얼마만큼의 무게가 측정되는지 알기 위해서는 HX711를 여러개 연결해야하지만, 예산상, 시간상의 이유로 어려움)
2. 응답시간의 문제점 - 응답시간이 길어지면 알림을 울리는 타이밍이 늦어 위험요소가 존재할 수 있음

**Comment by songwon0327** [comment]
인공지능에 집중하지 않은 이유 
->  1) 인공지능을 넣는데 들어가는 노력과 시간 대비 보도 블록에서 인공지능이 큰 역할을 하지 못할 것으로 예상되어 제외함
2) 인공지능을 추가하더라도 현재 사용한 센서로는 정확한 판단이 불가능할 것으로 예상

무게 중심 방향 판단 후 제시
-> 예산과 개발 기간 문제로 관련된 센서를 추가하는 것이 어렵다고 판단되어서 이번 프로젝트에서는 적용이 불가능할 것으로 예상
