### ISSUE TITLE
로드셀 출력문제 관련 #2

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#16]
이전 문제 해결이 되지 않아 새로운 방식들을 찾아보는 중입니다.
https://blog.naver.com/roboholic84/220866767735
위 블로그 내용을 참조하여 진행중인데 시도해보셨으면 합니다

**Comment by DaHyun0110** [comment]
저희가 보유하고 로드셀이 세부적으로 좌표를 만들 수 없는 종류의 로드셀인것 같습니다. 우선적으로 반응이 일어나면 알람이 울리도록 코드를 짜보았습니다. @songwon0327 @DaHyun0110 @LBKME
