### ISSUE TITLE
14주차 activity

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#17]
14주차  activity로 저희들이 마지막으로 해야할 것을 정리해 보았습니다.

1. PPT 만들기
2. 코드 마무리
3. 요구사항 정의서 수정
4. 발표 역할 분배
5. READ.ME 작성
6. 프로젝트 결과 보고서 작성

PPT는 제가 쭉 맡았던 만큼 대본과 자료를 주시면 제가 추가적으로 첨삭하는 방식으로 진행 하면 될듯 싶습니다.

코드는 저도 거의 완성되어가는 중입니다! //로드셀의 무게를 읽어와야해서 값을 저장해줄 변수를 만들어 주셨으면 합니다. @songwon0327 

READ.ME는 @LBKME 범구씨께서 현재 적고 계십니다.

요구사항 정의서의 경우, 저희가 많은 부분에서 언질을 받았기 때문에 차근차근 보면서 뜯어 고쳐야할 부분이 많다고 봅니다.
다들 한번씩 보시고 금요일까지 바꿔야할 부분에 대하여 의논할 수 있었으면 합니다!

**Comment by DaHyun0110** [comment]
[https://o365cbnu-my.sharepoint.com/:w:/g/personal/2019037017_cbnu_ac_kr/ERF5a6N4xSlPlonoidJSs1YBaLkQaspwIMP4_HcKjL6p9w?e=OkKVbK](url)

요구사항 보고서에서 저희가 수정해야할 부분을 표시하고, 일부 제가 수정 해보았습니다. 이를 보고 추가적으로 수정 해주시면 좋을것 같습니다!
혹시나 모르니 저희 해보조 카톡방에도 해당 보고서 수정본을 올려놓도록 하겠습니다

@songwon0327 @LBKME

**Comment by LBKME** [comment]
결과보고서는 조금 시간이 있으니 여유있게 해도 될것같습니다. 일단은 코드를 다 작성하죠 토요일 전까지는 완성을 해야 할 것 같습니다

**Comment by DaHyun0110** [comment]
@songwon0327 @LBKME 코드는 모두 업로드 하였습니다. 결과 보고서는 오늘 오후에 작성하도록 합시다!
