### ISSUE TITLE
3주차 발표를 위한 이슈

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#2]
1.  문제: 필요성 / input_output
2. 해결방법: 순서도, 알고리즘 등으로 표현
3. 차별성
4. 예상 결과물

로 이루어 져야합니다.
@songwon0327 
@DobakJungdok 
@LBKME

**Comment by DaHyun0110** [comment]
1. 문제
  -  필요성: 시작 장애인의 유도 점자 블록 훼손으로 인하여 큰 사고가 일어날 수 있다.(뉴스보도 자료와 함께 강조) 이때문에, 압력센서로 발걸음을 감지하여 모니터링하다가 훼손된 유도 점자블록에서 차도 쪽으로 걸어 나갈 경우, 유도점자 블록에서 진동/ 경고음이 들리는 것으로 방지할수 있지 않을가 생각하게 되었다. 유도 점자 블록은 대부분 도로의 바깥에 해당하는 부분에 존재하므로, 시각장애인들뿐만이 아니라 아동이나 전자기기에 몰두하여 차도에 대한 주의를 기울이지 못하는 사람들에게 또한 경고를 줌으로써 교통사고를 예방할수 있는 효과를 줄수 있을것이다.
  - input: 발걸음 압력 감지 output: 알람/경고

2. 해결방법: 압력 감지 -> 발끝과 발코를 분리하여 발이 향하는 방향을 알아봄, 이것이 차도방향일 때 알람/경고음이 들린다.(이때 차도 방향인것을 알수있는 방법을 어찌해야할지 생각해보아야할 것같습니다.)
3. 이전에 있던 유도점자블록 특허가 하나 존재하는 것으로 압니다. 그것과 다른것을 찾아 강조하는 방법으로 가야할것같습니다.
4. 알아보기 쉽도록 PPT 애니메이션으로 영상을 만드는 것이 어떨까요?

**Comment by LBKME** [comment]
위 내용으로 진행해도 좋을 것 같습니다
