### ISSUE TITLE
README에 들어갈 내용 추천 받습니다

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#21]
내용이 조금 부실한 것 같은데 어떤 내용을 추가하면 좋을까요?

**Comment by DaHyun0110** [comment]
작동 방식
신호등에서 0의 신호를 받으면(빨간불) 보행자 신호가 움직이므로, 블록 시스템이 움직입니다.
차선의 신호등이 초록불이 될 경우 1의 신호를 받게되고, 시스템은 작동하지 않습니다.

신호는 COMBINE에서 저희는 개발 시간의 관계로 시리얼 모니터에서 받은 입력을 신호등으로 생각하고 블록의 작동 여부를 판단하였습니다.

ESP32로 작동하는 방법 또한 올렸는데, 이 또한, 블루투스를 통하여 신호등에서 신호를 받는것으로 구동 방식이 같습니다.
ESP32에서의 신호등은 앱을 통하여 구현하였습니다. ESP를 사용한다면 비단 신호등과의 연결이 아닌, 신호 제어 시스템에 부착하여 기능할수 있다고 생각됩니다.

스피커는 if문을 통하여 만일, 시스템이 실행되는 상황에서 우리가 개발한 위험 상황이 발생시 (HX711을 이용한 코드, 송원씨 파트) 미리 녹음해놓았던 위험 발생 알림이 울려지게 됩니다.

**Comment by DaHyun0110** [comment]
앱인벤터 관련 라이선스: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by DaHyun0110** [comment]
리드미에 평가 목록과 한계점을 추가적으로 적어도 좋을것이라 생각됩니다.

**Comment by LBKME** [comment]
피드백 잘 받았습니다. 시간관계상 여기서 closed 하겠습니다
