### ISSUE TITLE
15주차 발표 관련 ISSUE

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#22]
기말 발표와 관련하여 역할을 분배하고 안에 적을 내용을 함께 써보고자 합니다.

1. 필요성
2. Problem
3. 차별성
4. Solution
5. 결과물
  5-1. 계획 대비 결과물의 기능 구현상황
  5-2. 완성도 
    5-2-1. 완성된 모습(영상 또는 데모)
    5-2-2. Evaluation 결과
6. Challenging issues, 한계점 향후 개선방향
이 있으며 Evaluation 목록, 챌린지 이슈 ,한계점등은 리드미에 추가해도 좋을것 같습니다.

이번에 코드를 완성하면 서 많은 부분이 처음에 계획했던 바와 다르게 되었다고 생각합니다.
1. 기존의 것과 차별되는 점
2. Solution의 구동방식에 대한 자세한 설명
3. 평가 목록
4. 한계점
등에 대하여 자세한 서술이 있으면 좋을듯 싶습니다!

또한, 발표를 맡고싶은 부분이 있으시면 역할 분배에 있어 참고하겠습니다.

**Comment by DaHyun0110** [comment]
@songwon0327 @LBKME

**Comment by DaHyun0110** [comment]
평가 목록
1. 제품은 고장이 날때 멈출 수 있는가?
2. 제품은 무게를 정확히 측정 할 수 있는가?
3. 제품은 도보->차선 / 차선->도보 로 가는 발걸음을 정확히 가늠 할 수 있는가?
4. 제품은 위험한 상황에 있어 즉각적인 알람을 보낼 수 있는가?
5. 제품은 기후 상황등의 여러 환경에 있어서 정확히 작동 할 수 있는가?
등이 들어 갈수 있다고 봅니다. 

한계 점으로는 평가 에서 실패한 부분이 들어가는것이 좋다고 생각합니다. 
1. 고장 날 때 멈춘다 <- 리드미에서 발견한 부분이기도 한데, 이부분은 0또는 1이 아닌 다른 신호를 받았을때에 break를 걸어 중지하는 방법을 써보도록 하겠습니다. (완벽히 고장에 대처는 아니고 어느정도 대처 가능할듯 싶음.)
2. 무게를 정확히 측정할 수 있는가? 로드셀이 정상적으로 작동된다는 하에 가능하다고 봅니다.
3. 도보->차선 / 차선-> 도보의 정확한 구분이 가능한가? 로드셀의 한계로 인하여 불가능하다. 이를 챌린지 이슈로 두어도 좋다고 봅닌다.
4. 즉각적인 알람: 가능하다고 봅니다.
5. 환경에 있어서 -> 센서를 아래에 붙일것이기 때문에 왠만한 충격에 있어 완고할것으로 보이므로 가능하다고 봅니다.
@songwon0327 @LBKME  다들 저의 의견에 대하여 가능한지 불가능한지 생각해 보시고 추가적으로 의견을 덧붙여주시면 PPT에 큰 도움이 될것같습니다.

**Comment by LBKME** [comment]
Challenge 이슈에는 인공지능을 추가할 수 있는 방안을 고려하는 것(차도로 가는지 안가는지에 대한 판단)과 신호등을 구현하는 또다른 방법을 추가하는 것도 좋아보입니다.

1. 고장날 때 멈춘다에서 시스템이 고장난다는 것은 센서를 1개 더 추가해서 각각의 센서가 서로 작동이 되는지 안되는지를 판단하면 좋을 것 같습니다. 예를들어 초음파 센서를 장착하여 초음파 센서가 물체를 감지했음에도 무게 센서가 작동을 안하면 고장나서 시스템을 멈춘다는 식으로 하면 좋을 것 같습니다.

2. 무게는 정확히 측정이 가능할 것으로 예상됩니다.
3. 앞서 말씀드렸듯이 챌린지 이슈로 해도 될 것 같습니다. 인공지능을 넣는다는 가정을 하는 것으로요
4. 즉각적 알림은 이미 완성했던 것 같습니다.
5. 환경에 있어서 충격방지는 센서가 외부로 드러나지 않는다 따라서 센서의 고장 확률이 적다. 정도로 적으면 좋을 것 같습니다.
