### ISSUE TITLE
3주차 발표에 대한 이슈

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#3]
3주차 ppt발표에서 3가지 질문이 들어왔습니다.

1. 발 모양을 인식할 만큼의 정교한 센서가 존재하는가?

2. 발 모양이 찍힐 만큼 보도블럭의 크기가 큰가?

3. 신발 밑창의 모양이 다 다른데 어떻게 인식할 것인가?

이에대한 의견을 작성해주셨으면 합니다

**Comment by LBKME** [comment]
일단 제가 한 답변은 아래와 같습니다

1. 발 모양을 인식할 만큼의 정교한 센서가 존재하는가?

-압력센서를 여러개 일정한 위치에 설치하여 좌표의 형식으로 입력받는다

2. 발 모양이 찍힐 만큼 보도블럭의 크기가 큰가?

-발 모양이 온전히 찍힐 필요는 없다. 어느정도만 찍혀도 인식이 되게 만들 것이다.

3. 신발 밑창의 모양이 다 다른데 어떻게 인식할 것인가?

-밑창은 다르더라도 결국 압력은 골고루 받는다. 신발 밑창의 모양은 큰 영향을 끼치지 않을 것으로 예상한다.

**Comment by songwon0327** [comment]
3번 질문에 답변을 추가하자면, 신발 밑창 모양이 신발마다 조금씩 차이는 있지만, 모든 신발은 앞꿈치의 형태가  뒷꿈치의 형태보다 길이가 긴 편이므로 앞, 뒤를 판별하는데에 문제 없을 것이라고 생각합니다.

**Comment by DaHyun0110** [comment]
2번의 질문에 제 의견을 말 해보자면, 인공신경망 모델을 사용하였을 경우, 학습을 통하여 발의 일부만 있어도 그것을 인식하는것을 목표로 잡고 있기때문에, 보도 블럭의 크기와는 상관이 없을것이라 생각됩니다.


다행스럽게도 들어오지않은 질문이지만, 발자국의 모양과 같은 유사한 물체의 압력/무게가 가해졌을때, 이를 어떻게 할것인지도 생각해 봐야할 것 같습니다. 물체는 사람과는 다르게 압력이 일정하고 변동이 없는 경우가 보통이므로(일상생활에서의 사람은 정자세로 있어도 압력이 일정하진 않았습니다.) 이것을 기준으로 물체와 사람을 분류하면 어떨까요?

**Comment by LBKME** [comment]
1번에 관해 저의 다른 의견을 말씀드리면, 압력센서가 저희가 생각하는 것과는 달라서 좌표는 조도센서를 활용하는 것도 괜찮아 보입니다.
