### ISSUE TITLE
4주차 요구사항 정의서 작성 이슈

### ISSUE THREAD

**Issue by songwon0327** [songwon0327/industrial-project#4]
4주차 멘토링 전에 요구사항 정의서 초안을 작성해야 합니다.
작성 관련해서 의견이 있으면 말씀 부탁 드립니다.

**Comment by LBKME** [comment]
산학프로젝트

첫 요구사항 정의서

1.서론
1.1문서목적 및 범위
본 문서는 산학프로젝트 과목에서 사용자의 요구사항을 정의하고 분석하기 위한 문서로, 프로젝트 개발 계획부터 결과 도출, 관리까지, 사용자 요구사항의 전반적인 내용을 담고 있다.

1.2대상시스템 개요
시스템 정의
해당 시스템은 시각장애인이 길을 걷던 중, 보도블럭이 훼손되어 시각장애인이 사고를 입는 것을 방지하여, 보도블럭이 훼손되더라도 시각장애인에게 안내를 주는 아두이노 기반 스마트 점자블록이다.

주요 기능 설명
1)시각장애인(이하 ‘사용자’)에게 음성 알림을 제공한다
  사용자가 보도블럭을 밟으면 이에 맞춰 시각장애인에게 음성 알림을 제공하여 사용자에게 경고알림이나 현 시점의 도로정보를 제공한다.

2)사용자가 걷고있는 위치를판단한다
사용자가 걷고있는 위치가 도로의 끝이고 횡단보도일 경우 사용자에게 경고 알림을 주어 사용자의 안전에 기여한다.

3)점자보도블럭의 훼손에 대응한다.
점자보도블럭의 점자부분이 훼손되어 사용자가 점자블록인지 이해를 하지 못하더라도 점자블록을 걷고 있으면 이에 상응하는 알림을 제공한다.
사용자가 점자블럭을 걷고 있는지는 다음과 같은 방법으로 판단한다
-압력센서를 이용해 점자보도블럭 위의 물체가 사람인지 아닌지를 무게로 판단한다.
-총 16개로 만들어진 조도센서를 통하여 사용자의 발모양을 판단해 발이 도로의 끝을 향하고 있으면 음성정보를 제공한다.


1.3용어 정의


2.기능적 요구사항
2-1)점자보도블럭 이용 관련 기능
1)사용자 분석 기능
사용자가 사람인지 아닌지를 판단하는 기능
-무게를 통해 약 20kg이상인지를 판단.
사용자의 발 방향을 분석하는 기능
-조도 센서를 통해 조도센서를 좌표값으로 활용하여 사용자의 발 방향이 도로의 끝부분일 경우 경고 알림
사용자 인식 기능
-평소에는 모니터링 중에 블록에 압력이 가해지면 기능
2-2)사용자 데이터 분석 기능
-시스템은 사용자들의 데이터를 수집한다.
-수집한 데이터를 토대로 발모양에 대한 데이터를 정돈한다.

3.비기능적 요구사항
3-1)운영환경에 대한 요구사항
시스템은 아두이노를 통해 동작한다.

3-2) 성능 요구사항
시스템은 최소 응답시간을 2초 내로 한다.
시스템은 최소 1사람. 최대 2사람까지 이용한다.
3-3) 보안 요구사항
없음
3-4) 문화 및 정책적 요구사항
안내 음성은 공통 경고음을 택한다.
3-5) 품질 요구사항
시스템은 1년 365일 언제나 작동해야 한다.
시스템은 밤에도 작동을 가능해야 한다.
시스템은 비가 와도 작동 가능하도록 방수가 되어야 한다.
시스템은 장애가 발생하면 즉시 작동을 멈춰야 한다.

일단 작성해 봤습니다. 다른 의견도 부탁드립니다

**Comment by DaHyun0110** [comment]
초안이 너무 좋으십니다! 거기에 추가로 넣은 사항과 여타 궁금한 점을 나열해보았습니다.

[ ] 대괄호 안에 들어가는 문장은 인공신경망을 사용할 시 추가하면 좋지 않을까 싶어 따로 표시 해놓았습니다.

**>> 추가>>1.3 용어정리에서 저희가 만들어갈 점자블록을 '경고 점형 점자 블록'이라는 이름으로 용어 정의를 추가하는 것이 좋다고 생각합니다!**

1)사용자 분석 기능
사용자가 사람인지 아닌지를 판단하는 기능
- 무게를 통해 약 20kg이상인지를 판단.
**>> 추가>> - 조도 센서의 좌표값을 활용하여 [인공신경망으로 학습된 점자블록의 SW가] 해당 물체가 사람의 발(신발)인지 그 외 기타 물체인지 판단.**
사용자의 발 방향을 분석하는 기능
-조도 센서를 통해 조도센서를 좌표값으로 활용하여 사용자의 발 방향이 도로의 끝부분일 경우 경고 알림
사용자 인식 기능
-평소에는 모니터링 중에 블록에 압력이 가해지면 기능

약간의 의문점이 있는데,
-**총 16개로** 만들어진 조도센서를 통하여 사용자의 발모양을 판단해 발이 도로의 끝을 향하고 있으면 음성정보를 제공한다.
에서 위험 블록을 의미하는 **점형블록은 점의갯수가 6*6 36개**인데 16개인 이유가 따로 잇을까요? 더 많으면 발모양의 인지에 참고가 되지 않을까 싶어서 같이 적어봅니다!

**Comment by songwon0327** [comment]
요구사항 정의서 초안 잘 읽었습니다!

하나 의견을 말씀드리자면 
3-2) 성능 요구사항 에서 최소 응답 시간을 2초 내로 작성해주셨는데, 조금 느슨한 느낌이 있어서 (사용자가 보도 블록을 밟고 다음 발을 내딛기 까지의 시간을 생각해 보았을 때) 최소 응답 시간을 좀 더 타이트하게 잡는 게 어떤가 생각합니다. 

추가로, 2-2) 사용자 데이터 분석 기능에서 사용자들의 데이터를 수집한다고 하셨는데, 보도 블록 설치 후 사용자들이 보도 블록을 밟을 때마다 상시 발 모양 데이터를 수집한다는 의미로 이해하면 되는 걸까요?

+ 당장 중요한 건 아니지만, 현재 센서 동작 기준 무게를 20kg로, 하한선만 정한 상태인데 상한선도 정해두면 더욱 좋을 것 같습니다. ( 차량 등이 밟을 상황을 대비해서)

**Comment by LBKME** [comment]
보내주신 의견들 잘 들었습니다. 의견 참고하여 의견서를 작성할테니 작성되면 올리겠습니다

**Comment by LBKME** [comment]
질문에 대한 답변을 드리자면 
1. 보도블럭의 조도센서가 36개가 아닌 16개인 이유는 간단하게 예산때문입니다. 가능하다면 더 늘리는 것도 좋겠지만요
2. 사용자 데이터 수집이 맞습니다. 발 모양을 얻는 거라고 보시면 됩니다
3. 무게를 하한선 20kg으로 정한건 아무래도 무게 센서가 10 20 50 100으로 있는데 가격이 기하급수적으로 늘어나기  때문입니다. 때문에 20kg으로 정한 이유도 이 때문입니다.
