### ISSUE TITLE
멘토링 일지를 위한 이슈

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#5]
멘토링 일지에 넣을 내용에 대하여 생각해 의논해보고자 이슈를 발행하였습니다.
여러분의 의견 부탁드립니다!
@songwon0327 @DobakJungdok @LBKME

**Comment by LBKME** [comment]
일단 멘토링 진행해주신 분의 성함은 기억이 나는데 소속은 기억이 안납니다. 소속에 대한 정보 알고 계신분은 알려주세요. 그리고 제가 기억하는 내용은 센서를 어떤식으로 응용하라고 하셨는데 이송원님 혹시 파일 보내주실수있나요?

**Comment by songwon0327** [comment]
확인이 늦었네요 죄송합니다. 소속에 대한 정보는 저도 잘 기억이 나지 않네요.. 
멘토링 메모 내용 함께 올리겠습니다. 
[4주차 멘토링 내용.txt](https://github.com/songwon0327/industrial-project/files/9713998/4.txt)
참고해주세요!
