### ISSUE TITLE
산학프로젝트 중간 발표

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#6]
이번 중간 발표에서 적어야 할 내용들을 논의해야 합니다.
배점 기준을 확인하고 회의에서 발의된 중요 부분을 적자면
1. 필요성, problem 같은 변화가 별로 없는 경우에 대한 논의
2. 차별성을 어떻게 할 것인가
3. 솔루션과 골루션에 영향을 끼친 맨토링에 대해
이렇게 이야기를 해봐야 할 것 같습니다.

그리고 다음 이슈 생성 담당자분은 역할 분배에 대한 이슈를 생성해 주시기 바랍니다.

**Comment by LBKME** [comment]
또한 요구사항정의서를 작성해야하는데 이는 제가 하겠으니 나머지에 대한 의논을 두분께서 해주시기 바랍니다

**Comment by DaHyun0110** [comment]
1. 필요성, problem 같은 변화가 별로 없는 경우에 대한 논의
멘토링 상으로도 충분히 의미있고 실현가능하다했으니 그대로 나두는 것이 나을 것 같습니다
2. 차별성을 어떻게 할 것인가
기존의 일반적인 보도블럭에서 스마트 보도블록으로 바뀐다는 차별성이 가장 큼으로 이에 대하여 부각시키고,
기존에 존재하는 알람 시스템은 신호등에 달린 스마트센서가 작동하는 방식인데 이와는 아예 다를 뿐더러, 보통 보도블럭 보다 더 바깥으로 나가야 작동하는 경우가 많았던 것같습니다.
이에 대하여 알아보고 난 후, 저희의 시스템이 더 일찍 작동하므로써 예방에 효과가 좋다는 것을 입증하면 되지않을까 싶습니다.
3. 솔루션과 골루션에 영향을 끼친 맨토링에 대해
멘토링의 경우 센서에서 무게센서를 통해 무게중심을 감시하여 이로 발의 방향을 정하는게 어떻냐고 나왔던것 같은데 조도 센서나 압력센서보다 더 현실성 있다고 판단됩니다.
멘토링땐 4개라고 하셨으나, 이가 4개로 모든 블럭이 다 인식되는지 확인후 완성모델은 조금 더 추가하는 방향으로 하는것도 괜찮다고 생각됩니다.

**Comment by LBKME** [comment]
아 그리고 산학프로젝트에 관해 지원을 받을 수 있는지 소프트웨어 중심 사업단에 문의해본 결과 지원은 어렵다는 답변을 받았습니다.

**Comment by songwon0327** [comment]
무게 센서를 이용해서 무게 중심을 감지하는 방법 아주 좋다고 생각합니다. 
차별성에서 일단 기존 보도 블럭은 훼손되거나 이물질의 영향으로  돌기를 시각장애인이 인식하기 어렵게 되면 보도 블럭의 기능을 못하게 된다는 점에 반해 스마트 보도 블록은 알림 시스템이 적용되어 있으므로 돌기를 인식하지 못하게 되어도 기능을 제대로 할 수 있다는 점이 가장 큰 차별점일 것 같습니다.
