### ISSUE TITLE
중간 발표 파트 분배에 대한 이슈

### ISSUE THREAD

**Issue by songwon0327** [songwon0327/industrial-project#7]
중간 발표 때 3명이 같이 발표하면 좋을 듯 한데 어떻게 생각하시나요?
괜찮으시다면 파트 분배를 어떻게 하면 좋을지 의견 이야기 해주시면 감사하겠습니다.

**Comment by DaHyun0110** [comment]
좋습니다
목차1-6중 제가 2차별성과 3예상 결과물을 맡겠습니다!

**Comment by LBKME** [comment]
그럼 제가 목차 1-2를 맡겠습니다. 나머지는 이송원님이 해주시면 될 것 같습니다
