### ISSUE TITLE
중간 발표 문제점으로 나온것들에 대한 토론

### ISSUE THREAD

**Issue by DaHyun0110** [songwon0327/industrial-project#8]
중간 발표 문제점으로 나온것들에 대한 토론해보고자 합니다
우선 제 생각은 아래와 같습니다.

1. 기존에 모션센서로 감지하는 것이 있는데 굳이?

 -> 해당 바리게이트 근처의 모션은 너무 차도와 가깝다. 특히나 사거리일떄 우측으로 가는 차일경우 해당 위치에 있으면 발이 씹힐수도 있고, 반응이 생각보다 느리기 때문에 이를 무시하고 갈수 있다.

2. 비보행 신호 받고 말고의 연결은 어떤식으로 할건데?

 -> 블루투스나 물리적 연결을 통하여 진행 될것임. 아마 블루투스로 하는 것이 나을 듯 -> 기존 모션 탐지기쪽에 있을텐데 이와 연결을 하기.  

3. 유도점자블록의 크기가 생각보다 작은데 이건 어떻게 할것인가 만일 블록을 넘어가면 어쩌게?
 -> 우리의 목표는 시각장애인임. 그리고 만일 넘어간다고 하더라고 이는 위험 지역에 있는 것이나 마찬가지이기 떄문에 말해줄거임 그냥 뛰어 넘어 버린 것이면, 애초에 시각장애인들은 그럴 일이 없음.

더 기억나는 질문이나 좋은 방안이 있다면 함꼐 상의하여도 좋을 것 같습니다!
@songwon0327 
@LBKME
@DobakJungdok

**Comment by LBKME** [comment]
내용 잘 읽었습니다. 발표에서 말씀드렸던거처럼 저도 의견에 상동합니다.
