### ISSUE TITLE
1차 회의에 대한 이슈와 문제점 토론

### ISSUE THREAD

**Issue by LBKME** [songwon0327/industrial-project#9]
금요일날 저희가 회의를 할 내용(이슈)는 다음과 같습니다.
1. 앞으로의 개발일정
2. 아두이노 구매를 위한 자금조달
3. 최종보고서 초안을 위한의견
4. 아두이노 장치를 위한 소프트웨어 설계 역할분배

위 4개의 내용을 회의할 생각이니 의견을 자유롭게 생각해오시면 좋을것 같습니다.
또한 2.에 관해 공모전을 나가는 것을 생각하고 있는데 어떻게 생각하시나요?

**Comment by DaHyun0110** [comment]
[개발일정]
10주차 : 개발 모델 선정, 아두이노 자금 모금 및 구매
11주차-12주차: 소프트 웨어 및 인공지능 모델 1차 개발
이후 수정, 개선 등의 일정을 거치면 되지 않을까 싶습니다

소프트웨어 설계 역할 분배는 인공지능 개발 및 학습 황다현 이송원
아두이노 물리회로도 설계및 보드 프로그래밍: 이범구
를 주로 하되 서로 도울 부분은 도우고 나눌 부분은 나눠서 역할을 분배하면 좋다고 생각됩니다.

**Comment by LBKME** [comment]
좋은 것같습니다. 개발일정이 좀 늦었지만 빠르게 해야할 거같습니다
